name: using actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults: #pass default configs to all job
            run:
                working-directory: using-actions/react-app #set working-directory key word to react app folder wo we can install deps and run test
        steps:
            - name: checkout the code from repo
              uses: actions/checkout@v4 #uses key word defines the action, v4 is the action version
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x' #pass latest node version with key word with
            - name: install dependencies
              run: npm ci
            - name: run automated unit tests
              run: npm run test
