name: event filters and activity types
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Run"