name: workflow event

on:
    - workflow_dispatch
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: show the trigger name
            run: echo "triggered by ${{ github.event_name }}" #will show push
